on: 
  push:
  workflow_dispatch:
    inputs:
      apps:
        description: 'App to deploy'
        type: string
        default: '["customer_api","invoice_api"]'
        required: true

env:
  apps: ${{ github.event_name == 'push' && '["customer_api","invoice_api"]' || inputs.apps}} # https://docs.github.com/en/actions/learn-github-actions/expressions#example

name: all_apps_cicd

jobs:
  env_vars: 
    name: Check env variables is available
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Apps env var value ${{ env.apps }}'
  
  build_unittest_and_push:
    uses: ./.github/workflows/build_unittest_and_push.yml
    with:
      apps: ${{ env.apps }}