on: [workflow_dispatch]
name: all_apps_cicd

jobs:
  build_and_unittest_linux:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build with dotnet
      uses: Amadevus/pwsh-script@v2.0.1
      id: dotnet-build
      with:
        script: dir "*.csproj" -Recurse | %{dotnet build  $PSItem.FullName}
    - run: echo '${{ steps.dotnet-build.outputs.result }}'
    
    #- name: Build all projects
     # run: dotnet build

    - name: Run unit tests
      uses: Amadevus/pwsh-script@v2.0.1
      id: dotnet_test
      with:
        script: |
                 dir "*.Tests.csproj" -Recurse | %{dotnet test  $PSItem.FullName --logger ("trx;LogFileName=" + ($PSItem.Name -replace ".csproj", ".trx")) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --no-restore --no-build}
                 dir "*.Tests.trx" -Recurse | %{ copy-item -Path $PSItem.FullName };
    - run: echo '${{ steps.dotnet_test.outputs.result }}'

    - name: Test Report
      uses: dorny/test-reporter@v1.6.0
      if: success() || failure()  # run this step even if previous step failed
      with:
        name: Unit Tests Linux  # Name of the check run which will be created
        path: ./*.Tests.trx  # Path to test results
        reporter: dotnet-trx  # Format of test results
