on: 
  push:
  workflow_dispatch:
    inputs:
      apps:
        description: 'App to deploy'
        type: string
        default: '["customer_api","invoice_api"]'
        required: true

env:
  apps: ${{ github.event_name == 'push' && '["customer_api","invoice_api"]' || inputs.apps}} # https://docs.github.com/en/actions/learn-github-actions/expressions#example

name: all_apps_cicd

jobs:
  build_unittest_and_push:
    permissions:
      id-token: write
      contents: read
      checks: write
    runs-on: "ubuntu-latest"
    steps:
      - shell: pwsh
        run: |
          echo 'apps from input ${{ inputs.apps }}'
          echo 'apps from env $APPS'
    # uses: ./.github/workflows/build_unittest_and_push.yml
    # with:
    #   apps: $apps