on: 
  push:
  workflow_dispatch:
    inputs:
      apps:
        description: 'App to deploy'
        type: string
        default: '["customer_api","invoice_api"]'
        required: true

name: all_apps_cicd

jobs:
  build_unittest_and_push:
    permissions:
      id-token: write
      contents: read
      checks: write
    runs-on: "ubuntu-latest"
    steps:
      - shell: pwsh
        run: |
          echo 'apps from input`` ${{ inputs.apps }}'
          echo 'apps from env ${{ env.apps }}'
    # uses: ./.github/workflows/build_unittest_and_push.yml