on: [workflow_dispatch, push]
name: all_apps_cicd

jobs:
  build_and_unittest_linux:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build with dotnet
      uses: Amadevus/pwsh-script@v2.0.1
      id: dotnet_build
      with:
        script: dir "*.csproj" -Recurse | %{dotnet build ($PSItem.FullName)}
    - run: echo '${{ steps.dotnet_build.outputs.result }}'
    
    
