on: 
  push:
  workflow_dispatch:
    inputs:
      apps:
        description: 'App to deploy'
        type: string
        default: '["customer_api", "invoice_api"]'
        required: true

env:
  apps: ${{ github.event_name == 'push' && '["customer_api"]' || inputs.apps}} # https://docs.github.com/en/actions/learn-github-actions/expressions#example

name: all_apps_cicd

jobs:
  env_vars: # Since passing env variables to reusable workflows not supported # https://github.com/orgs/community/discussions/26671
    name: Expose env variables
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ env.apps }}
    steps:
      - run: echo "Exposing env vars to reusable workflows"
  
  build_unittest_and_push:
    permissions:
      id-token: write
      contents: read
      checks: write
    needs: [env_vars]
    uses: ./.github/workflows/build_unittest_and_push.yml
    with:
      apps: ${{ needs.env_vars.outputs.apps }}